/**
 * basic 模块行为快照用例（锁定 v1 旧实现行为，供 2.0 TS 重写对照）
 *
 * 格式：{ args: [...args], note?: '说明' }
 * - 内联函数必须自包含（生成器按 toString 序列化，无法还原闭包）；this 仅配合 context 参数使用
 * - 旧实现的怪癖行为（返回 undefined / 0 / NaN / 抛错 / 类型误判）均按原样记录
 * - 日期一律用写死 ISO 的字面量；无随机 / 当前时间 / DOM 依赖
 *
 * ⚠️ 工具链限制（生成前需知）：gen-fixtures.mjs 调用前会对参数做 deepClone，
 * 该实现只认 Array/Date/普通对象——RegExp/Map/Set/Symbol/Error/arguments/FormData/Promise
 * 实例会被拍平成 {} 再传入；scripts/lib/serialize.mjs 的 revive 却能还原 RegExp/Map/Set。
 * 受影响的"正例"已在 note 中标注：当前生成会记成 false，需先补齐 deepClone/revive 再生成，
 * 否则这些快照会让正确的新实现误报失败。
 */
export default {
  module: 'basic',
  methods: {
    isNaN: [
      { args: [NaN], note: 'NaN 判定为 true' },
      { args: [0], note: '0 是数字，false' },
      { args: ['abc'], note: '字符串先进 isNumber 门卫（不像全局 isNaN 会强转），false' },
      { args: [undefined], note: '非数字类型 false' },
      { args: [Infinity], note: 'Infinity 是合法数字，false' },
    ],
    isFinite: [
      { args: [0], note: 'true' },
      { args: [1.5], note: '小数也有限，true' },
      { args: [Infinity], note: 'Infinity 非有限，false' },
      { args: ['5'], note: '数字字符串不过 isNumber 门卫，false' },
      { args: [NaN], note: 'NaN 非有限，false' },
    ],
    isUndefined: [
      { args: [undefined], note: 'true' },
      { args: [null], note: 'null 不算 undefined，false' },
      { args: [0], note: 'false' },
      { args: [''], note: '空字符串是已定义值，false' },
    ],
    isArray: [
      { args: [[]], note: '空数组 true' },
      { args: [[1, 2, 3]], note: 'true' },
      { args: ['ab'], note: '字符串 false' },
      { args: [{ 0: 'a', length: 1 }], note: '类数组对象不算数组，false' },
      { args: [null], note: 'false' },
    ],
    isFloat: [
      { args: [3.14], note: 'true' },
      { args: [-0.5], note: '负小数 true' },
      { args: [3], note: '整数 false' },
      { args: ['3.5'], note: '怪癖：数字字符串过全局 isNaN 后按 % 1 判定，true' },
      { args: [Infinity], note: '怪癖：Infinity 的 % 1 为 NaN 非整数，true' },
      { args: [null], note: 'false' },
    ],
    isInteger: [
      { args: [42], note: 'true' },
      { args: [-7], note: '负整数 true' },
      { args: [3.5], note: 'false' },
      { args: ['3'], note: '怪癖：数字字符串 % 1 === 0，true' },
      { args: [true], note: '怪癖：true % 1 === 0，true' },
      { args: [null], note: 'false' },
    ],
    isFunction: [
      { args: [function () {}], note: '普通函数 true' },
      { args: [(a, b) => a + b], note: '箭头函数 true' },
      { args: [class Foo { bar () {} }], note: 'class 的 typeof 也是 function，true' },
      { args: [null], note: 'false' },
      { args: ['function'], note: '字符串 false' },
    ],
    isBoolean: [
      { args: [true], note: 'true' },
      { args: [false], note: 'false 值也是 boolean 类型，true' },
      { args: [0], note: 'false' },
      { args: ['true'], note: '字符串 false' },
      { args: [undefined], note: 'false' },
    ],
    isString: [
      { args: ['abc'], note: 'true' },
      { args: [''], note: '空字符串仍是字符串，true' },
      { args: [123], note: 'false' },
      { args: [null], note: 'false' },
      { args: [['a']], note: '数组 false' },
    ],
    isNumber: [
      { args: [123], note: 'true' },
      { args: [NaN], note: '怪癖：NaN 的 typeof 是 number，true' },
      { args: [Infinity], note: 'true' },
      { args: ['123'], note: '数字字符串 false' },
      { args: [null], note: 'false' },
    ],
    isRegExp: [
      { args: [/ab+c/g], note: 'true（⚠️ 工具链限制：deepClone 会把 RegExp 参数拍平成 {}，生成前需修 serialize/deepClone，否则记录为 false）' },
      { args: ['ab'], note: '字符串 false' },
      { args: [{}], note: '普通对象 false' },
      { args: [null], note: 'false' },
    ],
    isObject: [
      { args: [{}], note: 'true' },
      { args: [[]], note: '怪癖：数组 typeof 也是 object，true' },
      { args: [new Date('2024-03-05T08:30:00')], note: 'Date 也是 object，true' },
      { args: [null], note: '怪癖：typeof null === "object"，直接判 true（与 isNull 相反）' },
      { args: ['obj'], note: '字符串 false' },
      { args: [function () {}], note: 'typeof function 不是 object，false' },
    ],
    isPlainObject: [
      { args: [{ a: 1 }], note: '字面量对象 constructor === Object，true' },
      { args: [{}], note: 'true' },
      { args: [[]], note: 'constructor 是 Array，false' },
      { args: [new Date('2024-03-05T08:30:00')], note: 'constructor 是 Date，false' },
      { args: [null], note: 'false' },
    ],
    isDate: [
      { args: [new Date('2024-03-05T08:30:00')], note: 'true' },
      { args: [new Date('invalid date')], note: '怪癖：Invalid Date 仍是 Date 实例，true' },
      { args: ['2024-03-05'], note: '日期字符串不算 Date 对象，false' },
      { args: [1719878400000], note: '时间戳数字 false' },
      { args: [null], note: 'false' },
    ],
    isValidDate: [
      { args: [new Date('2024-03-05T08:30:00')], note: 'true' },
      { args: [new Date('invalid date')], note: 'Invalid Date 的 getTime 为 NaN，false' },
      { args: ['2024-03-05'], note: '字符串直接不是 Date，false' },
      { args: [null], note: 'false' },
    ],
    isError: [
      { args: [new Error('boom')], note: 'true（⚠️ 工具链限制：Error 实例被 deepClone 拍平、revive 也不还原，两侧一致得 false，正例需工具链支持）' },
      { args: ['boom'], note: '字符串 false' },
      { args: [{}], note: 'false' },
      { args: [null], note: 'false' },
    ],
    isTypeError: [
      { args: [new TypeError('wrong type')], note: 'true（⚠️ 工具链限制：同 isError，实例参数被拍平，当前生成记 false）' },
      { args: [new Error('plain')], note: '普通 Error 的 constructor 不是 TypeError，false' },
      { args: [{}], note: 'false' },
      { args: [null], note: 'false' },
    ],
    isEmpty: [
      { args: [{}], note: '空对象 true' },
      { args: [[]], note: '空数组 true' },
      { args: [''], note: '空字符串 true' },
      { args: [null], note: '怪癖：for-in 对 null 不迭代不抛错，true' },
      { args: [0], note: '怪癖：原始值非对象也 true' },
      { args: [[0]], note: '非空数组 false' },
    ],
    isNull: [
      { args: [null], note: 'true' },
      { args: [undefined], note: 'undefined 不算 null，false' },
      { args: [0], note: 'false' },
      { args: [''], note: 'false' },
      { args: [false], note: 'false' },
    ],
    isSymbol: [
      { args: [Symbol('flag')], note: 'true（⚠️ 工具链限制：normalize 把 Symbol 记为 Unknown、revive 还原成普通对象，生成会得 false 且比较器两侧不对称，需先修 serialize）' },
      { args: ['flag'], note: '字符串 false' },
      { args: [null], note: 'false' },
      { args: [undefined], note: 'false' },
    ],
    isArguments: [
      { args: [(function () { return arguments })(1, 2, 3)], note: 'true（⚠️ 工具链限制：arguments 被 deepClone 拍平成普通对象，当前生成记 false）' },
      { args: [[1, 2, 3]], note: '数组 false' },
      { args: [{ 0: 1, 1: 2 }], note: '索引键对象不是 arguments，false' },
      { args: [null], note: 'false' },
    ],
    isElement: [
      { args: [{ nodeName: 'DIV', nodeType: 1 }], note: '鸭子判定 nodeName 字符串 + nodeType 数字，true' },
      { args: [{ nodeName: 'SPAN' }], note: '缺 nodeType，false' },
      { args: [{ nodeType: 1 }], note: '缺 nodeName，false' },
      { args: ['DIV'], note: '字符串 false' },
      { args: [null], note: 'false' },
    ],
    isDocument: [
      { args: [{ nodeName: '#document', nodeType: 9 }], note: 'node 环境下 staticDocument 为 0 恒返回 false（jsdom/浏览器下为 true——环境敏感，比较器仅应跑在 node 环境）' },
      { args: [{ nodeType: 1 }], note: '元素节点 false' },
      { args: [null], note: 'false' },
    ],
    isWindow: [
      { args: [{}], note: '怪癖+环境敏感：node 下 staticWindow 为 0，短路返回数字 0 而非 false' },
      { args: [null], note: '同样返回 0' },
      { args: ['x'], note: '非对象也返回 0' },
    ],
    isFormData: [
      { args: [new FormData()], note: 'true（⚠️ 工具链限制：FormData 实例被 deepClone 拍平，当前生成记 false；且依赖运行环境有全局 FormData，node>=18）' },
      { args: [{}], note: 'false' },
      { args: [null], note: 'false' },
      { args: ['form'], note: '字符串 false' },
    ],
    isMap: [
      { args: [new Map([['a', 1]])], note: 'true（⚠️ 工具链限制：Map 被 deepClone 拍平成 {}，当前生成记 false；revive 却能还原 Map，比较器会误报，需先修 deepClone）' },
      { args: [new WeakMap()], note: '近邻类型 false' },
      { args: [{}], note: '普通对象 false' },
      { args: [null], note: 'false' },
    ],
    isWeakMap: [
      { args: [new WeakMap()], note: 'true（⚠️ 工具链限制：WeakMap 被 deepClone 拍平、normalize 丢构造器，两侧一致得 false，正例需工具链支持）' },
      { args: [new Map()], note: 'Map 不是 WeakMap，false' },
      { args: [null], note: 'false' },
    ],
    isSet: [
      { args: [new Set([1, 2])], note: 'true（⚠️ 工具链限制：同 isMap，当前生成记 false）' },
      { args: [new WeakSet()], note: 'WeakSet 不是 Set，false' },
      { args: [[]], note: '数组 false' },
      { args: [null], note: 'false' },
    ],
    isWeakSet: [
      { args: [new WeakSet()], note: 'true（⚠️ 工具链限制：同 isWeakMap，正例需工具链支持）' },
      { args: [new Set()], note: 'Set 不是 WeakSet，false' },
      { args: [null], note: 'false' },
    ],
    isLeapYear: [
      { args: ['2024-02-29'], note: '闰年日期字符串 true' },
      { args: ['2023-06-15'], note: '平年 false' },
      { args: [new Date('2024-03-05T08:30:00')], note: 'Date 对象按 getFullYear 判定，true' },
      { args: ['2024'], note: '怪癖：纯年字符串可按默认格式位置解析，true' },
      { args: [2024], note: '怪癖：数字 2024 不满足 11-15 位时间戳规则，toStringDate 得 Invalid Date、getFullYear 为 NaN，false' },
      { args: ['abc'], note: '非法输入 false' },
    ],
    isMatch: [
      { args: [{ name: 'spark', age: 3, city: 'sz' }, { name: 'spark', age: 3 }], note: '键值都包含于目标，true' },
      { args: [{ name: 'spark', age: 3 }, { name: 'spark', age: 4 }], note: '值不等，false' },
      { args: [{ a: 1 }, {}], note: '怪癖：空匹配源恒 true' },
      { args: [null, { a: 1 }], note: 'null 目标退化为 isEqual(null, source)，false' },
      { args: [[1, 2, 3], [1, 2]], note: '数组按索引字符串键匹配，true' },
    ],
    isEqual: [
      { args: [[1, 2, 3], [1, 2, 3]], note: '数组深比较 true' },
      { args: [{ a: { b: 1 } }, { a: { b: 1 } }], note: '嵌套对象深比较 true' },
      { args: [{ a: 1 }, { a: 1, b: 2 }], note: '键数不同 false' },
      { args: [NaN, NaN], note: '怪癖：NaN 走 === 比较，false' },
      { args: [new Date('2024-03-05T08:30:00'), new Date('2024-03-05T08:30:00')], note: 'Date 转数值比较，true' },
      { args: [1, '1'], note: '跨类型严格比较 false' },
    ],
    isEqualWith: [
      { args: [[10, 20], [11, 21], function (v1, v2) { if (typeof v1 === 'number' && typeof v2 === 'number') { return Math.abs(v1 - v2) < 2 } }], note: '数值容差比较，true' },
      { args: [{ a: 1 }, { a: 2 }, function (v1, v2, key) { if (key === 'a') { return true } }], note: '指定键自定义判定救回不等值，true' },
      { args: [[1, 2, 3], [1, 2, 3], function () { return false }], note: '怪癖：自定义函数在顶层（key 为 undefined）返回 false 会短路深比较，false' },
      { args: [1, 2, function () { return true }], note: '原始值经包装比较器，true' },
      { args: [null, null, function () { return false }], note: '怪癖：=== 相等先行返回，自定义函数被跳过，true' },
    ],
    isDateSame: [
      { args: ['2024-03-05 08:30:00', '2024-03-05 08:30:00'], note: '默认格式化后字符串相等，true' },
      { args: ['2024-03-05', '2024-03-06'], note: '不同日 false' },
      { args: [new Date('2024-03-05T08:30:00'), new Date('2024-03-05T23:59:59'), 'yyyy-MM-dd'], note: '按天比较，true' },
      { args: [null, '2024-03-05'], note: '空值直接 false' },
      { args: ['abc', '2024-03-05'], note: '非法日期格式化为 Invalid Date，false' },
      { args: ['2024-01-01', '2024-08-15', 'yyyy'], note: '按年比较，true' },
    ],
    getType: [
      { args: [null], note: "'null'" },
      { args: ['str'], note: "'string'" },
      { args: [[1, 2]], note: "'array'（先于 object 判定）" },
      { args: [new Date('2024-03-05T08:30:00')], note: "'date'" },
      { args: [function () {}], note: "'function'" },
      { args: [undefined], note: "'undefined'" },
    ],
    getSize: [
      { args: ['abc'], note: '字符串取 length，3' },
      { args: [[1, 2, 3]], note: '数组取 length，3' },
      { args: [{ a: 1, b: 2, c: 3 }], note: '对象遍历计数，3' },
      { args: [{}], note: '0' },
      { args: [null], note: '0' },
      { args: [''], note: '空字符串 0' },
    ],
    toStringJSON: [
      { args: ['{"a":1,"b":[1,2]}'], note: '合法 JSON 字符串转对象' },
      { args: ['not json'], note: '解析失败静默回退 {}' },
      { args: [{ c: 3 }], note: '怪癖：普通对象入参原样返回' },
      { args: [''], note: '空字符串 {}' },
      { args: ['null'], note: '怪癖：JSON.parse("null") 得 null 原样返回' },
      { args: [123], note: '非字符串回退 {}' },
    ],
    toJSONString: [
      { args: [{ a: 1, b: 'x' }], note: '对象序列化' },
      { args: [[1, 2]], note: '数组序列化' },
      { args: [null], note: 'eqNull 空值返回空串' },
      { args: [undefined], note: '同上返回空串' },
      { args: ['str'], note: '字符串序列化带引号' },
      { args: [{ a: undefined }], note: '怪癖：undefined 值键被 JSON.stringify 丢弃得 {}' },
    ],
    first: [
      { args: [[3, 4, 5]], note: '取首元素 3' },
      { args: [{ a: 1, b: 2 }], note: '对象按 values 取第一个值 1' },
      { args: [[]], note: '空数组 undefined' },
      { args: ['abc'], note: '怪癖：字符串也走 values 取首字符 "a"' },
      { args: [null], note: 'undefined' },
    ],
    last: [
      { args: [[3, 4, 5]], note: '取末元素 5' },
      { args: [{ a: 1, b: 2 }], note: '对象取最后一个值 2' },
      { args: [[]], note: '空数组 undefined' },
      { args: ['abc'], note: '怪癖：字符串取末字符 "c"' },
      { args: [null], note: 'undefined' },
    ],
    each: [
      { args: [[1, 2, 3], function (v, i) { return v * i }], note: '怪癖：返回值丢失——arrayEach 无 return，整体返回 undefined' },
      { args: [{ a: 1, b: 2 }, function (v, k) { return k }], note: '对象走 objectEach，同样返回 undefined' },
      { args: [[1, 2, 3], function (v) { return this.prefix + v }, { prefix: 'x' }], note: 'context 经原生 forEach 传入（副作用不可见，仅锁定返回值 undefined）' },
      { args: [null, function (v) { return v }], note: '空值原样返回 null' },
      { args: ['abc', function (c) { return c }], note: '字符串走 objectEach 逐字符迭代，返回 undefined' },
    ],
    lastEach: [
      { args: [[1, 2, 3], function (v, i) { return v + i }], note: '倒序遍历，返回 undefined' },
      { args: [{ a: 1, b: 2 }, function (v, k) { return v }], note: '对象按 keys 倒序，返回 undefined' },
      { args: [[], function (v) { return v }], note: '空数组返回 undefined' },
      { args: [null, function (v) { return v }], note: '空值原样返回 null' },
    ],
    range: [
      { args: [5], note: '单参即 stop，[0,1,2,3,4]' },
      { args: [1, 5], note: '含头不含尾 [1,2,3,4]' },
      { args: [0, 10, 3], note: '步长 3 得 [0,3,6,9]' },
      { args: [0], note: 'stop 为 0 得 []' },
      { args: [5, 1], note: 'start >= stop（实际与 stop 而非 len 比较）直接 []' },
      { args: [3.7], note: '怪癖：小数经 >>0 截断，得 [0,1,2]' },
    ],
    property: [
      { args: ['name'], note: '返回取值函数（⚠️ 快照只记录返回函数的 toString，且源码被 vite-node SSR 改写混入 __vite_ssr_import__——新版源码不可能一致，建议 overrides 跳过或改专项测试）' },
      { args: ['a.b', 'def'], note: '带默认值，同样只记录函数源码' },
      { args: [0], note: '数字键，同样只记录函数源码' },
    ],
    isPromise: [
      { args: [{ then: function () {} }], note: 'thenable 鸭子判定 true' },
      { args: [new Promise(function (resolve) { resolve(1) })], note: '真 Promise 实例 true（⚠️ 工具链限制：实例被 deepClone 拍平成 {}，当前生成记 false）' },
      { args: [{ then: 'not a function' }], note: 'then 非函数 false' },
      { args: [null], note: 'false' },
      { args: [function () {}], note: '普通函数无 then，false' },
    ],
    evalReplacer: [
      { args: ['2+2'], note: '表达式求值得 4' },
      { args: ['({"a":1,"b":[1,2]})'], note: 'json 字符串须包一层括号，得对象' },
      { args: ['/ab+c/g'], note: '正则字面量字符串得 RegExp（输出侧可正常快照）' },
      { args: ['var a = 1;'], note: '语句被禁止，抛 SyntaxError（Throw 也按行为记录）' },
      { args: [123], note: '非字符串原样返回' },
      { args: ['[1,2,3]'], note: '数组字面量得数组' },
    ],
  },
}
